/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include "test.h"


void
test_prog_1( char* host )
{
	CLIENT *clnt;
	r_val  *result_1;
	entry  print_1_arg;
	clnt = clnt_create(host, TEST_PROG, TEST_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}

	print_1_arg.name = malloc(sizeof(char) * 64);
	print_1_arg.number = malloc(sizeof(char) * 64);

	strcpy(print_1_arg.name, "David");
	strcpy(print_1_arg.number, "42");
	print_1_arg.next = NULL;

	result_1 = print_1(&print_1_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	else {
		puts("results : ");
		printf("%i, %s\n", result_1->num, result_1->message);
	}
	clnt_destroy( clnt );
}


main( int argc, char* argv[] )
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	test_prog_1( host );
}
