/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST_H_RPCGEN
#define _TEST_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct entry {
	char *name;
	char *number;
	struct entry *next;
};
typedef struct entry entry;
#ifdef __cplusplus
extern "C" bool_t xdr_entry(XDR *, entry*);
#elif __STDC__
extern  bool_t xdr_entry(XDR *, entry*);
#else /* Old Style C */
bool_t xdr_entry();
#endif /* Old Style C */


struct r_val {
	int num;
	char *message;
};
typedef struct r_val r_val;
#ifdef __cplusplus
extern "C" bool_t xdr_r_val(XDR *, r_val*);
#elif __STDC__
extern  bool_t xdr_r_val(XDR *, r_val*);
#else /* Old Style C */
bool_t xdr_r_val();
#endif /* Old Style C */


#define TEST_PROG ((rpc_uint)0x55550011)
#define TEST_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define PRINT ((rpc_uint)1)
extern "C" r_val * print_1(entry *, CLIENT *);
extern "C" r_val * print_1_svc(entry *, struct svc_req *);

#elif __STDC__
#define PRINT ((rpc_uint)1)
extern  r_val * print_1(entry *, CLIENT *);
extern  r_val * print_1_svc(entry *, struct svc_req *);

#else /* Old Style C */
#define PRINT ((rpc_uint)1)
extern  r_val * print_1();
extern  r_val * print_1_svc();
#endif /* Old Style C */

#endif /* !_TEST_H_RPCGEN */
