/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include "test.h"

r_val *
print_1_svc(entry *argp, struct svc_req *rqstp)
{

	static r_val  result;

	printf("args = %s, %s\n", argp->name, argp->number);

	result.num = 23409;
	result.message = malloc(sizeof(char) * 64);

	strcpy(result.message, "Heres your message, ass");

	return(&result);
}
